# Generated by Django 4.1.7 on 2023-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentmothername', models.CharField(max_length=30)),
                ('studentfathername', models.CharField(max_length=30)),
                ('studentclass', models.IntegerField()),
                ('studentage', models.IntegerField()),
                ('studentmobilenumber', models.IntegerField()),
                ('studentvillage', models.CharField(max_length=30)),
            ],
        ),
    ]
